### ISSUE TITLE
CT:  Cannot set properties of null (setting 'visible')

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/function-builder#154]
This failure started on 1/19/2023, and occurred again on 1/20/2023.  It does not occur on every CT cycle.

```
function-builder : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1674216113796/function-builder/function-builder_en.html?continuousTest=%7B%22test%22%3A%5B%22function-builder%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1674216113796%22%2C%22timestamp%22%3A1674220623716%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught TypeError: Cannot set properties of null (setting 'visible')
TypeError: Cannot set properties of null (setting 'visible')
at (EquationPanel.js:99:45)
at listener (TinyEmitter.ts:95:8)
at emit (ReadOnlyProperty.ts:311:22)
at _notifyListeners (ReadOnlyProperty.ts:262:13)
at unguardedSet (ReadOnlyProperty.ts:246:11)
at set (Property.ts:54:10)
at (Checkbox.ts:139:6)
at apply (PhetioAction.ts:157:16)
at execute (Checkbox.ts:207:31)
at listener (TinyEmitter.ts:95:8)
id: Bayes Puppeteer
Snapshot from 1/20/2023, 5:01:53 AM
```

**Comment by pixelzoom** [comment]
This occurred 2x in CT.  It hasn't occurred since, and I can't reproduce in my working copy.  Since there were no changes to function-builder around that time, I'm going to assume that this was due to some transient common-cod problem.  Closing.
