### ISSUE TITLE
CT: assertion failed in HelpfulEquation.ts

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/function-builder#159]
> function-builder : multitouch-fuzz : unbuilt
http://128.138.93.172/continuous-testing/ct-snapshots/1694079103930/function-builder/function-builder_en.html?continuousTest=%7B%22test%22%3A%5B%22function-builder%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1694079103930%22%2C%22timestamp%22%3A1694079509690%7D&brand=phet&ea&fuzz&fuzzPointers=2&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&supportsPanAndZoom=false
Uncaught Error: Assertion failed
Error: Assertion failed
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1694079103930/assert/js/assert.js:28:13)
at assert (HelpfulEquation.ts:73:20)
at Array.forEach
at forEach (HelpfulEquation.ts:39:18)
at (EquationPanel.ts:167:28)
at updateEquations (EquationPanel.ts:140:13)
at listener (TinyEmitter.ts:123:8)
at emit (Emitter.ts:61:21)
at emit (Builder.js:149:32)
at addFunctionInstance (MathBuilder.js:35:10)
[URL] http://128.138.93.172/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1694079103930%2Ffunction-builder%2Ffunction-builder_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz%26fuzzPointers%3D2%26supportsPanAndZoom%3Dfalse&testInfo=%7B%22test%22%3A%5B%22function-builder%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1694079103930%22%2C%22timestamp%22%3A1694079509690%7D

**Comment by pixelzoom** [comment]
In the above commit, I added an assertion message to provide more information.  I'll wait for CT to hit this again.

**Comment by pixelzoom** [comment]
Here's the error with the improved message:

```
function-builder : pan-and-zoom-fuzz : unbuilt
http://128.138.93.172/continuous-testing/ct-snapshots/1694117841237/function-builder/function-builder_en.html?continuousTest=%7B%22test%22%3A%5B%22function-builder%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1694117841237%22%2C%22timestamp%22%3A1694118294279%7D&brand=phet&ea&fuzz&fuzzPointers=2&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&supportsPanAndZoom=true
Uncaught Error: Assertion failed: unexpected previousOperator: ×
Error: Assertion failed: unexpected previousOperator: ×
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1694117841237/assert/js/assert.js:28:13)
at assert (HelpfulEquation.ts:73:20)
```

**Comment by pixelzoom** [comment]
Oops. The assertion message above was incorrect.  Fixed in the above commit:

```diff
-          assert && assert( previousOperand, `unexpected previousOperator: ${previousOperator}` );
+          assert && assert( previousOperand, `unexpected previousOperand: ${previousOperand}` );
```

**Comment by pixelzoom** [comment]
Here's the CT report with improved error message:

> function-builder : pan-and-zoom-fuzz : unbuilt
http://128.138.93.172/continuous-testing/ct-snapshots/1694184258960/function-builder/function-builder_en.html?continuousTest=%7B%22test%22%3A%5B%22function-builder%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1694184258960%22%2C%22timestamp%22%3A1694185197956%7D&brand=phet&ea&fuzz&fuzzPointers=2&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&supportsPanAndZoom=true
Uncaught Error: Assertion failed: unexpected previousOperand: 0
Error: Assertion failed: unexpected previousOperand: 0
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1694184258960/assert/js/assert.js:28:13)
at assert (HelpfulEquation.ts:73:20)

The problem is a faulty assertion.  `0` is a valid operand, so the assertion should be:

```diff
-          assert && assert( previousOperand, `unexpected previousOperand: ${previousOperand}` );
+          assert && assert( previousOperand !== null );
```

This was introduced during TypeScript conversion in https://github.com/phetsims/function-builder/commit/e87c4477. There may be other similar faulty assertions in HelpfulEquation.ts.

**Comment by pixelzoom** [comment]
I fixed 2 faulty assertions in the above commit.  I'll verify that CT is happy before closing.

**Comment by pixelzoom** [comment]
CT is happy. Closing.
