### ISSUE TITLE
CT: assertion failure for pan-and-zoom-fuzz test

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/function-builder#160]
```
function-builder : pan-and-zoom-fuzz : unbuilt
http://127.0.0.1/continuous-testing/ct-snapshots/1710128142852/function-builder/function-builder_en.html?continuousTest=%7B%22test%22%3A%5B%22function-builder%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1710128142852%22%2C%22timestamp%22%3A1710131525644%7D&brand=phet&ea&fuzz&fuzzPointers=2&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&supportsPanAndZoom=true
Error: Assertion failed
window.assertions.assertFunction<@http://127.0.0.1/continuous-testing/ct-snapshots/1710128142852/assert/js/assert.js:28:13
at window.assertions.assertFunction< (http://127.0.0.1/continuous-testing/ct-snapshots/1710128142852/assert/js/assert.js:28:13)
at assert (EquationPanel.ts:128:16)
at (TinyEmitter.ts:123:18)
at emit (ReadOnlyProperty.ts:328:22)
at _notifyListeners (ReadOnlyProperty.ts:275:13)
at unguardedSet (ReadOnlyProperty.ts:259:11)
at set (Property.ts:54:10)
at property (Checkbox.ts:140:24)
at apply (PhetioAction.ts:162:16)
at execute (Checkbox.ts:208:31)
at (TinyEmitter.ts:123:18)
at emit (Emitter.ts:62:21)
at emit (FireListener.ts:101:22)
at fire (FireListener.ts:149:13)
at callback (PressListener.ts:752:16)
at apply (PhetioAction.ts:162:16)
at execute (PressListener.ts:508:24)
at release (FireListener.ts:142:10)
at release (PressListener.ts:851:11)
at inputEvent (Input.ts:1907:69)
at dispatchToListeners (Input.ts:1853:9)
at dispatchEvent (Input.ts:1657:9)
at upEvent (Input.ts:518:13)
at apply (PhetioAction.ts:162:16)
at execute (Input.ts:1295:24)
at touchEnd (InputFuzzer.js:242:24)
at touchEnd (InputFuzzer.js:55:11)
at action (InputFuzzer.js:107:6)
at fuzzEvents (SimDisplay.ts:210:23)
at fuzzInputEvents (Sim.ts:986:44)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at boundRunAnimationLoop (Sim.ts:921:19)
at (Sim.ts:899:24)
at (Sim.ts:880:16)
at i (Sim.ts:896:21)
at (Sim.ts:880:16)
at i (Sim.ts:896:21)
at (Sim.ts:880:16)
at i (Sim.ts:896:21)
at (Sim.ts:880:16)
at i (Sim.ts:896:21)
at (Sim.ts:880:16)
at i (Sim.ts:896:21)
at (Sim.ts:880:16)
at i (Sim.ts:896:21)
at (Sim.ts:880:16)
at i (Sim.ts:896:21)
at (Sim.ts:880:16)
at i (Sim.ts:896:21)
at (Sim.ts:880:16)
at i (Sim.ts:896:21)
at (Sim.ts:880:16)
at (Sim.ts:973:13)
at start (function-builder-main.ts:40:6)
at callback (simLauncher.ts:67:8)
at launchSimulation (simLauncher.ts:88:26)
at listener (asyncLoader.ts:56:42)
at forEach (asyncLoader.ts:56:21)
at proceedIfReady (asyncLoader.ts:69:11)
at image (logoOnWhite_png.ts:6:0)
[URL] http://127.0.0.1/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1710128142852%2Ffunction-builder%2Ffunction-builder_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz%26fuzzPointers%3D2%26supportsPanAndZoom%3Dtrue&testInfo=%7B%22test%22%3A%5B%22function-builder%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1710128142852%22%2C%22timestamp%22%3A1710131525644%7D
[NAVIGATED] http://127.0.0.1/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1710128142852%2Ffunction-builder%2Ffunction-builder_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz%26fuzzPointers%3D2%26supportsPanAndZoom%3Dtrue&testInfo=%7B%22test%22%3A%5B%22function-builder%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1710128142852%22%2C%22timestamp%22%3A1710131525644%7D
[ATTACHED]
[NAVIGATED] http://127.0.0.1/continuous-testing/ct-snapshots/1710128142852/function-builder/function-builder_en.html?continuousTest=%7B%22test%22%3A%5B%22function-builder%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1710128142852%22%2C%22timestamp%22%3A1710131525644%7D&brand=phet&ea&fuzz&fuzzPointers=2&supportsPanAndZoom=true
[CONSOLE] enabling assert
[CONSOLE] [JavaScript Warning: "An AudioContext was prevented from starting automatically. It must be created or resumed after a user gesture on the page." {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1710128142852/chipper/dist/js/tambo/js/phetAudioContext.js" line: 15}]
[CONSOLE] [JavaScript Warning: "WebGL warning: <Create>: WebglAllowWindowsNativeGl:false restricts context creation on this system." {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1710128142852/chipper/dist/js/scenery/js/util/Utils.js" line: 446}]
[CONSOLE] [JavaScript Warning: "Failed to create WebGL context: WebGL creation failed:
* WebglAllowWindowsNativeGl:false restricts context creation on this system. ()
* Exhausted GL driver options. (FEATURE_FAILURE_WEBGL_EXHAUSTED_DRIVERS)" {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1710128142852/chipper/dist/js/scenery/js/util/Utils.js" line: 446}]
[CONSOLE] [JavaScript Warning: "WebGL warning: <Create>: WebglAllowWindowsNativeGl:false restricts context creation on this system." {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1710128142852/chipper/dist/js/scenery/js/util/Utils.js" line: 446}]
[CONSOLE] [JavaScript Warning: "Failed to create WebGL context: WebGL creation failed:
* WebglAllowWindowsNativeGl:false restricts context creation on this system. ()
* Exhausted GL driver options. (FEATURE_FAILURE_WEBGL_EXHAUSTED_DRIVERS)" {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1710128142852/chipper/dist/js/scenery/js/util/Utils.js" line: 446}]
[CONSOLE] continuous-test-load
[CONSOLE] Assertion failed
[CONSOLE] continuous-test-error
[PAGE ERROR] Error: Assertion failed

id: "Sparky Node Firefox"
Snapshot from 3/10/2024, 9:35:42 PM
```

**Comment by zepumph** [comment]
Not sure what you mean by "down in TinyEmitter", the assertion being triggered is https://github.com/phetsims/function-builder/blob/24d97e998d36b9dbf7c81f0e0f7fc32bc27a7555/js/common/view/equations/EquationPanel.ts#L128. That is just a listener firing from axon logic (where all listeners are fired from). The stack/queue logic is still on a branch. I fuzzed on my side for 10 minutes and didn't reproduce, which seems on par with what CT is showing, since it takes an overnight row to trigger the problem. I don't know how best to help you proceed, but it seems like a small and awkward multitouch bug to me. Let me know if I can do anything else here. I wouldn't say this is high priority.

**Comment by pixelzoom** [comment]
I wrote the relevant listener so that assertions are not necessary. Closing.
