### ISSUE TITLE
Automated Testing Sim Errors (3/29/2016 10:00 AM)

### ISSUE THREAD

**Issue by phet-steele** [phetsims/function-builder#23]
```
Uncaught Error: Assertion failed: startDrag: nodes in animationLayer should not be pickable
Error: Assertion failed: startDrag: nodes in animationLayer should not be pickable
    at window.assertions.assertFunction (http://phettest.colorado.edu/assert/js/assert.js:23:13)
    at Object.CardNode.options.startDrag (http://phettest.colorado.edu/function-builder/js/common/view/CardNode.js?bust=1459268551388:70:17)
    at MovableNode.addInputListener.SimpleDragHandler.start (http://phettest.colorado.edu/function-builder/js/common/view/MovableNode.js?bust=1459268551388:62:38)
    at SimpleDragHandler.inherit.startDrag (http://phettest.colorado.edu/scenery/js/input/SimpleDragHandler.js?bust=1459268551388:153:28)
    at SimpleDragHandler.inherit.tryToSnag (http://phettest.colorado.edu/scenery/js/input/SimpleDragHandler.js?bust=1459268551388:180:14)
    at SimpleDragHandler.inherit.down (http://phettest.colorado.edu/scenery/js/input/SimpleDragHandler.js?bust=1459268551388:197:12)
    at Input.inherit.dispatchToTargets (http://phettest.colorado.edu/scenery/js/input/Input.js?bust=1459268551388:846:31)
    at Input.inherit.dispatchEvent (http://phettest.colorado.edu/scenery/js/input/Input.js?bust=1459268551388:788:14)
    at Input.inherit.downEvent (http://phettest.colorado.edu/scenery/js/input/Input.js?bust=1459268551388:672:14)
    at Input.inherit.mouseDown (http://phettest.colorado.edu/scenery/js/input/Input.js?bust=1459268551388:315:14)
```

**Comment by phet-steele** [comment]
```
Uncaught Error: Assertion failed: endDrag: card should be in dragLayer
Error: Assertion failed: endDrag: card should be in dragLayer
    at window.assertions.assertFunction (http://phettest.colorado.edu/assert/js/assert.js:23:13)
    at Object.CardNode.options.endDrag (http://phettest.colorado.edu/function-builder/js/common/view/CardNode.js?bust=1459268551388:167:17)
    at MovableNode.addInputListener.SimpleDragHandler.end (http://phettest.colorado.edu/function-builder/js/common/view/MovableNode.js?bust=1459268551388:80:36)
    at SimpleDragHandler.inherit.endDrag (http://phettest.colorado.edu/scenery/js/input/SimpleDragHandler.js?bust=1459268551388:165:26)
    at Object.SimpleDragHandler.dragListener.up (http://phettest.colorado.edu/scenery/js/input/SimpleDragHandler.js?bust=1459268551388:74:19)
    at Input.inherit.dispatchToPointer (http://phettest.colorado.edu/scenery/js/input/Input.js?bust=1459268551388:811:29)
    at Input.inherit.dispatchEvent (http://phettest.colorado.edu/scenery/js/input/Input.js?bust=1459268551388:784:14)
    at Input.inherit.upEvent (http://phettest.colorado.edu/scenery/js/input/Input.js?bust=1459268551388:654:14)
    at Input.inherit.mouseUp (http://phettest.colorado.edu/scenery/js/input/Input.js?bust=1459268551388:326:14)
    at Display.extend.fuzzMouseEvents (http://phettest.colorado.edu/scenery/js/display/Display.js?bust=1459268551388:1100:25)
```

**Comment by pixelzoom** [comment]
Thanks. Introduced in https://github.com/phetsims/function-builder/commit/7f32b2cbc97cecdd9926a6937103078ec73e3388 (make cards stop at 'see inside' windows when animating).

**Comment by pixelzoom** [comment]
Note to self: This is probably because I removed `pickable:false` from SeeInsideLayer, in order to make cards draggable when they are stopped at windows.

**Comment by pixelzoom** [comment]
One-line fix in above commit. Ran with fuzzMouse for 10 minutes, no assertion failures. Closing.

**Comment by pixelzoom** [comment]
Note that fixing this caused #25 to appear.
