### ISSUE TITLE
Automated testing error

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/function-builder#7]
Might be a double-call of dispose?

```
TypeError: Cannot read property 'emit' of null
    at Rotate90.inherit.dispose (http://192.168.0.2:8080/function-builder/js/common/model/AbstractFunction.js?bust=1452540032728:67:32)
    at Object.MoveTo.onComplete (http://192.168.0.2:8080/function-builder/js/common/view/MovableFunctionNode.js?bust=1452540032728:80:32)
    at MovableFunctionNode. (http://192.168.0.2:8080/function-builder/js/common/view/MoveTo.js?bust=1452540032728:63:17)
    at update (http://192.168.0.2:8080/sherpa/lib/Tween-r12.js:356:31)
    at Object.TWEEN.update (http://192.168.0.2:8080/sherpa/lib/Tween-r12.js:76:27)
    at Sim.inherit.stepSimulation (http://192.168.0.2:8080/joist/js/Sim.js?bust=1452540032728:735:24)
    at Sim.inherit.runAnimationLoop (http://192.168.0.2:8080/joist/js/Sim.js?bust=1452540032728:661:12)
```

**Comment by pixelzoom** [comment]
Which automated test is failing? (In general, a helpful bit of information to provide.)  I was guessing `fuzzMouse`, but haven't been able to reproduce.

**Comment by pixelzoom** [comment]
It's the `fuzzMouse` test, reproduced more quickly when running with `screens=1`.

**Comment by pixelzoom** [comment]
Add assertions to guard against calling things that have been set to `null` by calling dispose.

**Comment by pixelzoom** [comment]
This happens on 'Reset All'.  The function instances get disposed of by PatternsScene (the model), but also by any associated MovableFunctionNodes (the view).

**Comment by pixelzoom** [comment]
This can be reproduced without `fuzzMouse` in the "Patterns" screen by:

• set MoveTo `duration:10` to slow down the animation to mortal speed
• drag a function out of the carousel
• release the function
• press the 'Reset All' button before the function returns to the carousel, PatternsScene will call dispose and the function will disappear
• wait a few seconds for the animation to complete, dispose will be called again from MovableFunctionNode add trigger the assertion failure

**Comment by pixelzoom** [comment]
Fixed, closing.  Thanks for reporting.

**Comment by jonathanolson** [comment]
Would "require.js fuzzMouse", "built fuzzMouse" or "build" be helpful for every automated testing error (from test-server)? Should I specify test-server?

**Comment by pixelzoom** [comment]
yes, knowing which test failed would save a bit of time.  I'm fine with knowing that "automated test" means "test-server", so that's up to you.
